export const ADD_MERCHANT = 'ADD_MERCHANT';
export const EDIT_MERCHANT = 'EDIT_MERCHANT';
export const DELETE_MERCHANT = 'DELETE_MERCHANT';
export const SET_MERCHANTS = 'SET_MERCHANTS';
export const AJAX_LOADING = 'AJAX_LOADING';